[@ww.label labelKey="push0ver.task.localdir" name="tasklocaldir"/]
[@ww.label labelKey="push0ver.task.username" name="taskusername"/]
[@ww.label labelKey="push0ver.task.password" name="taskpassword"/]
[@ww.label labelKey="push0ver.task.reponame" name="taskreponame"/]
[@ww.label labelKey="push0ver.task.url" name="taskurl"/]
[@ww.label labelKey="push0ver.mvnhome" name="mavenhome"/]
[@ww.label labelKey="push0ver.task.client" name="taskclient"/]
