[@ww.label labelKey="push0ver.task.localdir" name="tasklocaldir"/]
[@ww.label labelKey="push0ver.task.username" name="taskusername"/]
[@ww.label labelKey="push0ver.task.password" name="taskpassword"/]
[@ww.label labelKey="push0ver.task.releaserepo" name="taskreleaserepo"/]
[@ww.label labelKey="push0ver.task.noderepo" name="tasknoderepo"/]
[@ww.label labelKey="push0ver.task.url" name="taskurl"/]
[@ww.label labelKey="push0ver.task.client" name="allowAllConnect"/]
